language: php

jobs:
  include:
    - php: '7.3'
      env: XDEBUG=YES
    - php: '7.4'
      env: XDEBUG=YES
    - php: nightly
      env: XDEBUG=NO
  allow_failures:
    - php: nightly

install:
  - mkdir -p ./build/logs
  - composer self-update
  - if [ "$TRAVIS_PHP_VERSION" == "nightly" ]; then
      composer install --prefer-source --no-interaction --ignore-platform-reqs;
    else
      composer install --prefer-source --no-interaction;
    fi

script:
  - vendor/bin/phpcs -sp --report-junit=build/logs/phpcs.xml
  - if [ "$XDEBUG" == "YES" ]; then
      vendor/bin/phpunit --coverage-clover=build/logs/clover.xml --coverage-xml=build/logs/coverage-xml --log-junit=build/logs/junit.xml;
    else
      vendor/bin/phpunit;
    fi
  - vendor/bin/psalm --threads=4
  - if [ "$XDEBUG" == "YES" ]; then
      vendor/bin/infection --coverage=build/logs --threads=4  --no-progress --skip-initial-tests;
    fi

after_success:
  - if [ "$XDEBUG" == "YES" ]; then
      bash <(curl -s https://codecov.io/bash -s "build/logs");
    fi
  - if [ "$XDEBUG" == "YES" ]; then
      wget https://scrutinizer-ci.com/ocular.phar;
    fi
  - if [ "$XDEBUG" == "YES" ]; then
      php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml;
    fi
