version: '3'

services:
  php8.0:
    build:
      context: .
      dockerfile: php-8.0.Dockerfile
    volumes:
      - .:/app
    working_dir: /app
  php7.3:
    build:
      context: .
      dockerfile: php-7.3.Dockerfile
    volumes:
      - .:/app
    working_dir: /app
  php:
    build:
      context: .
      dockerfile: php-7.4.Dockerfile
    volumes:
      - .:/app
    working_dir: /app